#define VIAL_KEYBOARD_UID {0x82, 0x1C, 0x92, 0xC7, 0x6B, 0xC1, 0xB2, 0xA9}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 13 }

#define TAPPING_TERM 500

// #define DYNAMIC_KEYMAP_ENABLE
// #define DYNAMIC_KEYMAP_LAYER_COUNT 8
#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
    #undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define VIAL_TAP_DANCE_ENTRIES 5
#define VIAL_COMBO_ENTRIES 5
#define VIAL_KEY_OVERRIDE_ENTRIES 5

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
